# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KorhanTest < Formula
  desc ""
  homepage "https://github.com/shuetisha/homebrew-korhan-test"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuetisha/homebrew-korhan-test/releases/download/v1.0.3/homebrew-korhan-test_Darwin_x86_64.tar.gz"
      sha256 "3218306379494ed5b1b481066c8c25fef50b5e669f6de2006cc153a7cd30f1a6"

      def install
        bin.install "homebrew-korhan-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuetisha/homebrew-korhan-test/releases/download/v1.0.3/homebrew-korhan-test_Darwin_arm64.tar.gz"
      sha256 "12c40114b7255d1d7b0bad43c089f0cbf70e338ced6e6059046a8b3d9229a36a"

      def install
        bin.install "homebrew-korhan-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shuetisha/homebrew-korhan-test/releases/download/v1.0.3/homebrew-korhan-test_Linux_x86_64.tar.gz"
      sha256 "70bcd2a6e9f2a3f8a4cb7921aa4c971004e87c45ce589b43d1f13b636adf0783"

      def install
        bin.install "homebrew-korhan-test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuetisha/homebrew-korhan-test/releases/download/v1.0.3/homebrew-korhan-test_Linux_arm64.tar.gz"
      sha256 "0745458f0dd3947fb8b50b9d66e853d2e2fcf61f835d701b60643f487db8c24c"

      def install
        bin.install "homebrew-korhan-test"
      end
    end
  end
end
